update speculative workflow template to include run status check step

diff --git a/workflow-templates/terraform-cloud.speculative-run.workflow.yml b/workflow-templates/terraform-cloud.speculative-run.workflow.yml
--- a/workflow-templates/terraform-cloud.speculative-run.workflow.yml
+++ b/workflow-templates/terraform-cloud.speculative-run.workflow.yml
@@ -46,6 +46,9 @@ jobs:
 
       - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.3
         id: run
+        ## run may fail, if so continue to output PR comment
+        ## step.terraform-cloud-check-run-status will fail job after pr comment is created/updated.
+        continue-on-error: true
         with:
           workspace: ${{ env.TF_WORKSPACE }}
           configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
@@ -97,3 +100,11 @@ jobs:
               })
             }
 
+        ## Check Run Status, if not planned_and_finished fail the job
+      - id: terraform-cloud-check-run-status
+        if: ${{ steps.run.outputs.run_status != 'planned_and_finished'}}
+        run: |
+          echo "Terraform Cloud Run Failed or Requires Further Attention"
+          echo "Run Status: '${{ steps.run.outputs.run_status }}'"
+          echo "${{ steps.run.outputs.run_link }}"
+          exit 1
